### ISSUE TITLE
tabindex ?

### ISSUE THREAD

**Issue by CaMer0n** [e107inc/e107-test#8]
@Deltik @SimSync 
`tabindex` magically just showed up in the e_form test results. (causing mismatch errors) . 
Any suggestions as to what may have caused that recently?
Also, linkwords is now failing to save a pref during installation also. 

Thoughts?

**Comment by Deltik** [comment]
@CaMer0n: I ran a `git bisect` for the failing `pluginsTest: Linkwords` test and this was the result:

```bash
$ git bisect good
262dc7f36b7896388527c97d5d064d721427ccdd is the first bad commit
commit 262dc7f36b7896388527c97d5d064d721427ccdd
Author: Cameron <REDACTED>
Date:   Sun Jul 22 10:39:01 2018 -0700

    Closes #3305 Added a backward compatibility fix for buggy array storage data.

:040000 040000 3d5824385fe2736b10330557396e543463fcd12c f2ec758309524e2bfed6ed8ffecf19d2a2981fcb M      e107_handlers
```

----

As for the mystery `tabindex`, it seems no matter how far back I go in the commit history, it's always there.

**Comment by Deltik** [comment]
@CaMer0n and @SimSync: I figured out why `e_formTest: Select` and `e_formTest: Render element` are now failing.  It's due to [line 95](https://github.com/e107inc/e107-test/commit/deb544f2cf1203908a3b25bcf34c75eac35220b5#diff-37bbf5ca3877102e7b8f459c8368d468R95) of deb544f2cf1203908a3b25bcf34c75eac35220b5

**Comment by Deltik** [comment]
@CaMer0n and @SimSync: I figured out why `e_formTest: Select` and `e_formTest: Render element` are now failing.  It's due to [line 95](https://github.com/e107inc/e107-test/commit/deb544f2cf1203908a3b25bcf34c75eac35220b5#diff-37bbf5ca3877102e7b8f459c8368d468R95) of deb544f2cf1203908a3b25bcf34c75eac35220b5.

**Comment by Deltik** [comment]
@CaMer0n: By removing the `0` from [line 474 of 262dc7f36b7896388527c97d5d064d721427ccdd](https://github.com/e107inc/e107/commit/262dc7f36b7896388527c97d5d064d721427ccdd#diff-798502005750bc8a4404b74e42e0c3d7R474), the "`linkwords`" plugin fails to install its "addons".
